manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: shakushakupanda
      url-base: https://github.com/shakushakupanda
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar
    - name: kot149  # <-- new entry
      url-base: https://github.com/kot149
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: shakushakupanda
      revision: paw3222
    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main
  self:
    path: config
