manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: shakushakupanda
      url-base: https://github.com/shakushakupanda
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: shakushakupanda
      revision: paw3222
  self:
    path: config
